# Generated by Django 2.1.2 on 2018-10-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='https://picsum.photos/200/300/?random', max_length=200),
        ),
    ]
